title: Brendan Goubin
email: b.goubin.56@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cv.billos.fr" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  billos

author: Brendan Goubin
job: Développeur Web

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass

livereload: true
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
